# Generated by Django 4.2.2 on 2023-07-03 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalog_models',
            options={'verbose_name': 'Каталог программ'},
        ),
        migrations.AlterModelOptions(
            name='novosti_models',
            options={'verbose_name': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='post_models',
            options={'verbose_name': 'Заявки'},
        ),
    ]
