# Generated by Django 4.2.2 on 2023-07-03 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_catalog_models_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalog_models',
            options={'verbose_name': 'Каталог программ', 'verbose_name_plural': 'Каталог программ'},
        ),
        migrations.AlterModelOptions(
            name='novosti_models',
            options={'verbose_name': 'Новости', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='post_models',
            options={'verbose_name': 'Заявки', 'verbose_name_plural': 'Заявки'},
        ),
    ]
