# Generated by Django 4.2.3 on 2023-07-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_catalog_models_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog_models',
            name='announce',
            field=models.CharField(max_length=1000, verbose_name='Анонс'),
        ),
        migrations.AlterField(
            model_name='novosti_models',
            name='announce',
            field=models.CharField(max_length=1000, verbose_name='Анонс'),
        ),
    ]
