# Generated by Django 4.2.3 on 2023-07-06 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_catalog_models_announce_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Novosti_models',
        ),
    ]
