# Generated by Django 4.2.3 on 2023-07-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_catalog_models_ysl_alter_catalog_models_announce_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog_models',
            name='ysl',
            field=models.TextField(blank=True, null=True, verbose_name='Условия и режим реализации'),
        ),
        migrations.AlterField(
            model_name='catalog_models',
            name='zanyatia',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Количество занятий'),
        ),
    ]
