# Generated by Django 4.2.3 on 2023-07-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Novosti_models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Фото')),
                ('name', models.CharField(max_length=100, verbose_name='Название новости')),
                ('announce', models.CharField(max_length=1000, verbose_name='Анонс')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
                ('full', models.TextField(blank=True, null=True, verbose_name='Вся новость')),
                ('source', models.CharField(blank=True, max_length=100, null=True, verbose_name='Источник:')),
            ],
            options={
                'verbose_name': 'Новости',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
