# Generated by Django 4.2.3 on 2023-07-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novosti_models',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название новости'),
        ),
    ]
